/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

/**
 *
 * @author lrmendiburo
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMes = new javax.swing.JLabel();
        jComboBoxMeses = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelMontoDJ08Playa = new javax.swing.JLabel();
        jLabelMontoCR09Playa = new javax.swing.JLabel();
        jLabelMontoDJ05Playa = new javax.swing.JLabel();
        jLabelMontoTramitesPlaya = new javax.swing.JLabel();
        jLabelMontoServiciosPlaya = new javax.swing.JLabel();
        jLabelMontoOfimaticaPlaya = new javax.swing.JLabel();
        jLabelMontoOtrosPlaya = new javax.swing.JLabel();
        jLabelMontoGastosPlaya = new javax.swing.JLabel();
        jLabelMontoTotalPlaya = new javax.swing.JLabel();
        jLabelMontoServiciosAdAtPlaya = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabelMontoDJ08Redondel = new javax.swing.JLabel();
        jLabelMontoCR09Redondel = new javax.swing.JLabel();
        jLabelMontoDJ05Redondel = new javax.swing.JLabel();
        jLabelMontoTramitesRedondel = new javax.swing.JLabel();
        jLabelMontoServiciosRedondel = new javax.swing.JLabel();
        jLabelMontoOfimaticaRedondel = new javax.swing.JLabel();
        jLabelMontoOtrosRedondel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelMontoGastosRedondel = new javax.swing.JLabel();
        jLabelMontoTotalRedondel = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabelMontoServiciosAdAtRedondel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabelMontoDJ08Marianao = new javax.swing.JLabel();
        jLabelMontoCR09Marianao = new javax.swing.JLabel();
        jLabelMontoDJ05Marianao = new javax.swing.JLabel();
        jLabelMontoTramitesMarianao = new javax.swing.JLabel();
        jLabelMontoServiciosMarianao = new javax.swing.JLabel();
        jLabelMontoOfimaticaMarianao = new javax.swing.JLabel();
        jLabelMontoOtrosMarianao = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabelMontoGastosMarianao = new javax.swing.JLabel();
        jLabelMontoTotalMarianao = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabelMontoServiciosAdAtMarianao = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabelTotalGeneral = new javax.swing.JLabel();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuEstructura = new javax.swing.JMenu();
        jMenuItemOficinas = new javax.swing.JMenuItem();
        jMenuItemTrabajadores = new javax.swing.JMenuItem();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenuOperacionServiciosAsAt = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemDJ08 = new javax.swing.JMenuItem();
        jMenuItemCR09 = new javax.swing.JMenuItem();
        jMenuItemDJ05 = new javax.swing.JMenuItem();
        jMenuItemTramite = new javax.swing.JMenuItem();
        jMenuItemOfimatica = new javax.swing.JMenuItem();
        jMenuItemOtro = new javax.swing.JMenuItem();
        jMenuItemGasto = new javax.swing.JMenuItem();
        jMenuItemServicio = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuClientes = new javax.swing.JMenu();
        jMenuItemClienteTitular = new javax.swing.JMenuItem();
        jMenuItemClienteContratado = new javax.swing.JMenuItem();
        jMenuGeneral = new javax.swing.JMenu();
        jMenuItemGenerarListado = new javax.swing.JMenuItem();
        jMenuItemGeneralResumen = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor Principal");
        setResizable(false);

        jLabelMes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelMes.setText("Mes:");

        jComboBoxMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Oficina: Playa");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Operación:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Monto:");

        jLabel4.setText("DJ08");

        jLabel5.setText("CR09");

        jLabel6.setText("DJ05");

        jLabel7.setText("Trámites");

        jLabel8.setText("Servicios");

        jLabel9.setText("Ofimática");

        jLabel10.setText("Otros");

        jLabel11.setText("Gastos");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Total");

        jLabelMontoDJ08Playa.setText("00.00");

        jLabelMontoCR09Playa.setText("00.00");

        jLabelMontoDJ05Playa.setText("00.00");

        jLabelMontoTramitesPlaya.setText("00.00");

        jLabelMontoServiciosPlaya.setText("00.00");

        jLabelMontoOfimaticaPlaya.setText("00.00");

        jLabelMontoOtrosPlaya.setText("00.00");

        jLabelMontoGastosPlaya.setText("00.00");

        jLabelMontoTotalPlaya.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelMontoTotalPlaya.setText("00.00");

        jLabelMontoServiciosAdAtPlaya.setText("00.00");

        jLabel13.setText("Servicios Ad/At");

        jLabel14.setText("Otros");

        jLabel15.setText("Gastos");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("Total");

        jLabelMontoDJ08Redondel.setText("00.00");

        jLabelMontoCR09Redondel.setText("00.00");

        jLabelMontoDJ05Redondel.setText("00.00");

        jLabelMontoTramitesRedondel.setText("00.00");

        jLabelMontoServiciosRedondel.setText("00.00");

        jLabelMontoOfimaticaRedondel.setText("00.00");

        jLabelMontoOtrosRedondel.setText("00.00");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setText("Oficina: Redondel");

        jLabelMontoGastosRedondel.setText("00.00");

        jLabelMontoTotalRedondel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelMontoTotalRedondel.setText("00.00");

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setText("Operación:");

        jLabelMontoServiciosAdAtRedondel.setText("00.00");

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setText("Monto:");

        jLabel20.setText("Servicios Ad/At");

        jLabel21.setText("DJ08");

        jLabel22.setText("CR09");

        jLabel23.setText("DJ05");

        jLabel24.setText("Trámites");

        jLabel25.setText("Servicios");

        jLabel26.setText("Ofimática");

        jLabel27.setText("Otros");

        jLabel28.setText("Gastos");

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel29.setText("Total");

        jLabelMontoDJ08Marianao.setText("00.00");

        jLabelMontoCR09Marianao.setText("00.00");

        jLabelMontoDJ05Marianao.setText("00.00");

        jLabelMontoTramitesMarianao.setText("00.00");

        jLabelMontoServiciosMarianao.setText("00.00");

        jLabelMontoOfimaticaMarianao.setText("00.00");

        jLabelMontoOtrosMarianao.setText("00.00");

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel30.setText("Oficina: Marianao");

        jLabelMontoGastosMarianao.setText("00.00");

        jLabelMontoTotalMarianao.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelMontoTotalMarianao.setText("00.00");

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel31.setText("Operación:");

        jLabelMontoServiciosAdAtMarianao.setText("00.00");

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel32.setText("Monto:");

        jLabel33.setText("Servicios Ad/At");

        jLabel34.setText("DJ08");

        jLabel35.setText("CR09");

        jLabel36.setText("DJ05");

        jLabel37.setText("Trámites");

        jLabel38.setText("Servicios");

        jLabel39.setText("Ofimática");

        jLabel40.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel40.setText("Total General:");

        jLabelTotalGeneral.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTotalGeneral.setText("00.00");

        jMenuEstructura.setText("Estructura");

        jMenuItemOficinas.setText("Oficinas");
        jMenuEstructura.add(jMenuItemOficinas);

        jMenuItemTrabajadores.setText("Trabajadores");
        jMenuEstructura.add(jMenuItemTrabajadores);

        jMenuItemUsuarios.setText("Usuarios");
        jMenuEstructura.add(jMenuItemUsuarios);

        jMenuBarPrincipal.add(jMenuEstructura);

        jMenuOperacionServiciosAsAt.setText("Operación");

        jMenu1.setText("Ingreso");

        jMenuItemDJ08.setText("DJ08");
        jMenuItemDJ08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDJ08ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDJ08);

        jMenuItemCR09.setText("CR09");
        jMenuItemCR09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCR09ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCR09);

        jMenuItemDJ05.setText("DJ05");
        jMenuItemDJ05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDJ05ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDJ05);

        jMenuItemTramite.setText("Trámite");
        jMenuItemTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTramiteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemTramite);

        jMenuItemOfimatica.setText("Ofímatica");
        jMenuItemOfimatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOfimaticaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemOfimatica);

        jMenuItemOtro.setText("Otro");
        jMenuItemOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOtroActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemOtro);

        jMenuOperacionServiciosAsAt.add(jMenu1);

        jMenuItemGasto.setText("Gasto");
        jMenuItemGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGastoActionPerformed(evt);
            }
        });
        jMenuOperacionServiciosAsAt.add(jMenuItemGasto);

        jMenuItemServicio.setText("Servicio");
        jMenuItemServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemServicioActionPerformed(evt);
            }
        });
        jMenuOperacionServiciosAsAt.add(jMenuItemServicio);

        jMenuItem1.setText("Servicios Ad/At");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuOperacionServiciosAsAt.add(jMenuItem1);

        jMenuBarPrincipal.add(jMenuOperacionServiciosAsAt);

        jMenuClientes.setText("Clientes");

        jMenuItemClienteTitular.setText("Cliente Titular");
        jMenuClientes.add(jMenuItemClienteTitular);

        jMenuItemClienteContratado.setText("Cliente Contratado");
        jMenuClientes.add(jMenuItemClienteContratado);

        jMenuBarPrincipal.add(jMenuClientes);

        jMenuGeneral.setText("General");

        jMenuItemGenerarListado.setText("Generar Listado");
        jMenuGeneral.add(jMenuItemGenerarListado);

        jMenuItemGeneralResumen.setText("Generar Resumen");
        jMenuGeneral.add(jMenuItemGeneralResumen);

        jMenuBarPrincipal.add(jMenuGeneral);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(1, 1, 1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(1, 1, 1)))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabelMontoDJ08Playa)
                            .addComponent(jLabelMontoCR09Playa)
                            .addComponent(jLabelMontoDJ05Playa)
                            .addComponent(jLabelMontoTramitesPlaya)
                            .addComponent(jLabelMontoServiciosPlaya)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMontoOfimaticaPlaya)
                                    .addComponent(jLabelMontoOtrosPlaya)
                                    .addComponent(jLabelMontoGastosPlaya)
                                    .addComponent(jLabelMontoTotalPlaya)))
                            .addComponent(jLabelMontoServiciosAdAtPlaya)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addGap(52, 52, 52)
                        .addComponent(jLabelTotalGeneral))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(5, 5, 5)))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabelMontoDJ08Redondel)
                                    .addComponent(jLabelMontoCR09Redondel)
                                    .addComponent(jLabelMontoDJ05Redondel)
                                    .addComponent(jLabelMontoTramitesRedondel)
                                    .addComponent(jLabelMontoServiciosRedondel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabelMontoTotalRedondel))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel14)
                                                .addComponent(jLabel15)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel26)
                                            .addGap(1, 1, 1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(1, 1, 1)))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelMontoOfimaticaRedondel)
                                            .addComponent(jLabelMontoOtrosRedondel)
                                            .addComponent(jLabelMontoGastosRedondel)))
                                    .addComponent(jLabelMontoServiciosAdAtRedondel))
                                .addGap(18, 18, 18)))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelMes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17))
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel31)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel27)
                                        .addComponent(jLabel28)
                                        .addComponent(jLabel29)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel39)
                                    .addGap(1, 1, 1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(1, 1, 1)))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabelMontoDJ08Marianao)
                            .addComponent(jLabelMontoCR09Marianao)
                            .addComponent(jLabelMontoDJ05Marianao)
                            .addComponent(jLabelMontoTramitesMarianao)
                            .addComponent(jLabelMontoServiciosMarianao)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMontoOfimaticaMarianao)
                                    .addComponent(jLabelMontoOtrosMarianao)
                                    .addComponent(jLabelMontoGastosMarianao)
                                    .addComponent(jLabelMontoTotalMarianao)))
                            .addComponent(jLabelMontoServiciosAdAtMarianao))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMes)
                    .addComponent(jComboBoxMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelMontoDJ08Redondel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelMontoCR09Redondel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelMontoDJ05Redondel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelMontoTramitesRedondel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelMontoServiciosRedondel))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel25)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabelMontoServiciosAdAtRedondel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelMontoOfimaticaRedondel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelMontoOtrosRedondel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelMontoGastosRedondel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15)))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMontoTotalRedondel)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMontoDJ08Playa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMontoCR09Playa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMontoDJ05Playa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMontoTramitesPlaya)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMontoServiciosPlaya)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMontoServiciosAdAtPlaya)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMontoOfimaticaPlaya)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMontoOtrosPlaya)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMontoGastosPlaya)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelMontoTotalPlaya))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel29))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMontoDJ08Marianao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMontoCR09Marianao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMontoDJ05Marianao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMontoTramitesMarianao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMontoServiciosMarianao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMontoServiciosAdAtMarianao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMontoOfimaticaMarianao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMontoOtrosMarianao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMontoGastosMarianao)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelMontoTotalMarianao)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jLabelTotalGeneral))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemDJ08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDJ08ActionPerformed
        this.dispose();
        VentanaDJ08 ventanaDJ08 = new VentanaDJ08();
        ventanaDJ08.show();
    }//GEN-LAST:event_jMenuItemDJ08ActionPerformed

    private void jMenuItemCR09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCR09ActionPerformed
        this.dispose();
        VentanaCR09 ventanaCR09 = new VentanaCR09();
        ventanaCR09.show();
    }//GEN-LAST:event_jMenuItemCR09ActionPerformed

    private void jMenuItemDJ05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDJ05ActionPerformed
        this.dispose();
        VentanaDJ05 ventanaDJ05 = new VentanaDJ05();
        ventanaDJ05.show();
    }//GEN-LAST:event_jMenuItemDJ05ActionPerformed

    private void jMenuItemTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTramiteActionPerformed
        this.dispose();
        VentanaTramite ventanaTramite = new VentanaTramite();
        ventanaTramite.show();
    }//GEN-LAST:event_jMenuItemTramiteActionPerformed

    private void jMenuItemOfimaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOfimaticaActionPerformed
        this.dispose();
        VentanaOfimatica ventanaOfimatica = new VentanaOfimatica();
        ventanaOfimatica.show();
    }//GEN-LAST:event_jMenuItemOfimaticaActionPerformed

    private void jMenuItemOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOtroActionPerformed
        this.dispose();
        VentanaOtro ventanaOtro = new VentanaOtro();
        ventanaOtro.show();
    }//GEN-LAST:event_jMenuItemOtroActionPerformed

    private void jMenuItemGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGastoActionPerformed
        this.dispose();
        VentanaGasto ventanaGasto = new VentanaGasto();
        ventanaGasto.show();
    }//GEN-LAST:event_jMenuItemGastoActionPerformed

    private void jMenuItemServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemServicioActionPerformed
        this.dispose();
        VentanaServicio ventanaServicio = new VentanaServicio();
        ventanaServicio.show();
    }//GEN-LAST:event_jMenuItemServicioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        VentanaServicioAdAt ventanaServicioAdAt = new VentanaServicioAdAt();
        ventanaServicioAdAt.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxMeses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMes;
    private javax.swing.JLabel jLabelMontoCR09Marianao;
    private javax.swing.JLabel jLabelMontoCR09Playa;
    private javax.swing.JLabel jLabelMontoCR09Redondel;
    private javax.swing.JLabel jLabelMontoDJ05Marianao;
    private javax.swing.JLabel jLabelMontoDJ05Playa;
    private javax.swing.JLabel jLabelMontoDJ05Redondel;
    private javax.swing.JLabel jLabelMontoDJ08Marianao;
    private javax.swing.JLabel jLabelMontoDJ08Playa;
    private javax.swing.JLabel jLabelMontoDJ08Redondel;
    private javax.swing.JLabel jLabelMontoGastosMarianao;
    private javax.swing.JLabel jLabelMontoGastosPlaya;
    private javax.swing.JLabel jLabelMontoGastosRedondel;
    private javax.swing.JLabel jLabelMontoOfimaticaMarianao;
    private javax.swing.JLabel jLabelMontoOfimaticaPlaya;
    private javax.swing.JLabel jLabelMontoOfimaticaRedondel;
    private javax.swing.JLabel jLabelMontoOtrosMarianao;
    private javax.swing.JLabel jLabelMontoOtrosPlaya;
    private javax.swing.JLabel jLabelMontoOtrosRedondel;
    private javax.swing.JLabel jLabelMontoServiciosAdAtMarianao;
    private javax.swing.JLabel jLabelMontoServiciosAdAtPlaya;
    private javax.swing.JLabel jLabelMontoServiciosAdAtRedondel;
    private javax.swing.JLabel jLabelMontoServiciosMarianao;
    private javax.swing.JLabel jLabelMontoServiciosPlaya;
    private javax.swing.JLabel jLabelMontoServiciosRedondel;
    private javax.swing.JLabel jLabelMontoTotalMarianao;
    private javax.swing.JLabel jLabelMontoTotalPlaya;
    private javax.swing.JLabel jLabelMontoTotalRedondel;
    private javax.swing.JLabel jLabelMontoTramitesMarianao;
    private javax.swing.JLabel jLabelMontoTramitesPlaya;
    private javax.swing.JLabel jLabelMontoTramitesRedondel;
    private javax.swing.JLabel jLabelTotalGeneral;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenu jMenuEstructura;
    private javax.swing.JMenu jMenuGeneral;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemCR09;
    private javax.swing.JMenuItem jMenuItemClienteContratado;
    private javax.swing.JMenuItem jMenuItemClienteTitular;
    private javax.swing.JMenuItem jMenuItemDJ05;
    private javax.swing.JMenuItem jMenuItemDJ08;
    private javax.swing.JMenuItem jMenuItemGasto;
    private javax.swing.JMenuItem jMenuItemGeneralResumen;
    private javax.swing.JMenuItem jMenuItemGenerarListado;
    private javax.swing.JMenuItem jMenuItemOficinas;
    private javax.swing.JMenuItem jMenuItemOfimatica;
    private javax.swing.JMenuItem jMenuItemOtro;
    private javax.swing.JMenuItem jMenuItemServicio;
    private javax.swing.JMenuItem jMenuItemTrabajadores;
    private javax.swing.JMenuItem jMenuItemTramite;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JMenu jMenuOperacionServiciosAsAt;
    // End of variables declaration//GEN-END:variables
}
