/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

/**
 *
 * @author lrmendiburo
 */
public class VentanaAdicionarServicioAdAt extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAdicionarGasto
     */
    public VentanaAdicionarServicioAdAt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonAceptar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jLabelMes = new javax.swing.JLabel();
        jComboBoxOficina = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNota = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinnerDate = new javax.swing.JSpinner();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jLabelMes1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jButtonTitular = new javax.swing.JButton();
        jButtonContratado = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePagos = new javax.swing.JTable();
        jButtonAdicionarPago = new javax.swing.JButton();
        jButtonEditarPago = new javax.swing.JButton();
        jButtonEliminarPago = new javax.swing.JButton();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuEstructura = new javax.swing.JMenu();
        jMenuItemOficinas = new javax.swing.JMenuItem();
        jMenuItemTrabajadores = new javax.swing.JMenuItem();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenuOperacionServiciosAsAt = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemDJ08 = new javax.swing.JMenuItem();
        jMenuItemCR09 = new javax.swing.JMenuItem();
        jMenuItemDJ05 = new javax.swing.JMenuItem();
        jMenuItemTramite = new javax.swing.JMenuItem();
        jMenuItemOfimatica = new javax.swing.JMenuItem();
        jMenuItemOtro = new javax.swing.JMenuItem();
        jMenuItemGasto = new javax.swing.JMenuItem();
        jMenuItemServicio = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuClientes = new javax.swing.JMenu();
        jMenuItemClienteTitular = new javax.swing.JMenuItem();
        jMenuItemClienteContratado = new javax.swing.JMenuItem();
        jMenuGeneral = new javax.swing.JMenu();
        jMenuItemGenerarListado = new javax.swing.JMenuItem();
        jMenuItemGeneralResumen = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Adicionar Servicio Ad/At:");

        jButtonAceptar.setText("Aceptar");

        jButtonLimpiar.setText("Limpiar");

        jButtonVolver.setText("Vover");

        jLabelMes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelMes.setText("Oficina:");

        jComboBoxOficina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Playa", "Redondel", "Marianao" }));

        jTextAreaNota.setColumns(20);
        jTextAreaNota.setRows(5);
        jScrollPane1.setViewportView(jTextAreaNota);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Nota:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Fecha:");

        jSpinnerDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_WEEK_IN_MONTH));

        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jLabelMes1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelMes1.setText("Mes:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("ID:");

        jButtonTitular.setText("Titular");

        jButtonContratado.setText("Contratado");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("NIT:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Cliente:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Pagos:");

        jTablePagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Concepto", "Monto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTablePagos);

        jButtonAdicionarPago.setText("Adicionar");

        jButtonEditarPago.setText("Editar");

        jButtonEliminarPago.setText("Eliminar");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Nombre:");

        jMenuEstructura.setText("Estructura");

        jMenuItemOficinas.setText("Oficinas");
        jMenuEstructura.add(jMenuItemOficinas);

        jMenuItemTrabajadores.setText("Trabajadores");
        jMenuEstructura.add(jMenuItemTrabajadores);

        jMenuItemUsuarios.setText("Usuarios");
        jMenuEstructura.add(jMenuItemUsuarios);

        jMenuBarPrincipal.add(jMenuEstructura);

        jMenuOperacionServiciosAsAt.setText("Operación");

        jMenu1.setText("Ingreso");

        jMenuItemDJ08.setText("DJ08");
        jMenuItemDJ08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDJ08ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDJ08);

        jMenuItemCR09.setText("CR09");
        jMenuItemCR09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCR09ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCR09);

        jMenuItemDJ05.setText("DJ05");
        jMenuItemDJ05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDJ05ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDJ05);

        jMenuItemTramite.setText("Trámite");
        jMenuItemTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTramiteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemTramite);

        jMenuItemOfimatica.setText("Ofímatica");
        jMenuItemOfimatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOfimaticaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemOfimatica);

        jMenuItemOtro.setText("Otro");
        jMenuItemOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOtroActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemOtro);

        jMenuOperacionServiciosAsAt.add(jMenu1);

        jMenuItemGasto.setText("Gasto");
        jMenuItemGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGastoActionPerformed(evt);
            }
        });
        jMenuOperacionServiciosAsAt.add(jMenuItemGasto);

        jMenuItemServicio.setText("Servicio");
        jMenuItemServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemServicioActionPerformed(evt);
            }
        });
        jMenuOperacionServiciosAsAt.add(jMenuItemServicio);

        jMenuItem1.setText("Servicios Ad/At");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuOperacionServiciosAsAt.add(jMenuItem1);

        jMenuBarPrincipal.add(jMenuOperacionServiciosAsAt);

        jMenuClientes.setText("Clientes");

        jMenuItemClienteTitular.setText("Cliente Titular");
        jMenuClientes.add(jMenuItemClienteTitular);

        jMenuItemClienteContratado.setText("Cliente Contratado");
        jMenuClientes.add(jMenuItemClienteContratado);

        jMenuBarPrincipal.add(jMenuClientes);

        jMenuGeneral.setText("General");

        jMenuItemGenerarListado.setText("Generar Listado");
        jMenuGeneral.add(jMenuItemGenerarListado);

        jMenuItemGeneralResumen.setText("Generar Resumen");
        jMenuGeneral.add(jMenuItemGeneralResumen);

        jMenuBarPrincipal.add(jMenuGeneral);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(551, Short.MAX_VALUE)
                        .addComponent(jButtonAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabelMes1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabelMes))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinnerDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxOficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addGap(130, 130, 130))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonAdicionarPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonEditarPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonEliminarPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(15, 15, 15))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(73, 73, 73)
                                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(73, 73, 73)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jButtonTitular)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButtonContratado))
                                                    .addComponent(jTextFieldNit, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButtonAdicionarPago)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditarPago)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEliminarPago)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMes1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jSpinnerDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxOficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMes))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonContratado, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonTitular)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 15, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVolver)
                    .addComponent(jButtonLimpiar)
                    .addComponent(jButtonAceptar))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemDJ08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDJ08ActionPerformed
        this.dispose();
        VentanaDJ08 ventanaDJ08 = new VentanaDJ08();
        ventanaDJ08.show();
    }//GEN-LAST:event_jMenuItemDJ08ActionPerformed

    private void jMenuItemCR09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCR09ActionPerformed
        this.dispose();
        VentanaCR09 ventanaCR09 = new VentanaCR09();
        ventanaCR09.show();
    }//GEN-LAST:event_jMenuItemCR09ActionPerformed

    private void jMenuItemDJ05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDJ05ActionPerformed
        this.dispose();
        VentanaDJ05 ventanaDJ05 = new VentanaDJ05();
        ventanaDJ05.show();
    }//GEN-LAST:event_jMenuItemDJ05ActionPerformed

    private void jMenuItemTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTramiteActionPerformed
        this.dispose();
        VentanaTramite ventanaTramite = new VentanaTramite();
        ventanaTramite.show();
    }//GEN-LAST:event_jMenuItemTramiteActionPerformed

    private void jMenuItemOfimaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOfimaticaActionPerformed
        this.dispose();
        VentanaOfimatica ventanaOfimatica = new VentanaOfimatica();
        ventanaOfimatica.show();
    }//GEN-LAST:event_jMenuItemOfimaticaActionPerformed

    private void jMenuItemOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOtroActionPerformed
        this.dispose();
        VentanaOtro ventanaOtro = new VentanaOtro();
        ventanaOtro.show();
    }//GEN-LAST:event_jMenuItemOtroActionPerformed

    private void jMenuItemGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGastoActionPerformed
        this.dispose();
        VentanaGasto ventanaGasto = new VentanaGasto();
        ventanaGasto.show();
    }//GEN-LAST:event_jMenuItemGastoActionPerformed

    private void jMenuItemServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemServicioActionPerformed
        this.dispose();
        VentanaServicio ventanaServicio = new VentanaServicio();
        ventanaServicio.show();
    }//GEN-LAST:event_jMenuItemServicioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        VentanaServicioAdAt ventanaServicioAdAt = new VentanaServicioAdAt();
        ventanaServicioAdAt.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdicionarServicioAdAt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdicionarServicioAdAt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdicionarServicioAdAt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdicionarServicioAdAt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdicionarServicioAdAt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonAdicionarPago;
    private javax.swing.JButton jButtonContratado;
    private javax.swing.JButton jButtonEditarPago;
    private javax.swing.JButton jButtonEliminarPago;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonTitular;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JComboBox<String> jComboBoxOficina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelMes;
    private javax.swing.JLabel jLabelMes1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenu jMenuEstructura;
    private javax.swing.JMenu jMenuGeneral;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemCR09;
    private javax.swing.JMenuItem jMenuItemClienteContratado;
    private javax.swing.JMenuItem jMenuItemClienteTitular;
    private javax.swing.JMenuItem jMenuItemDJ05;
    private javax.swing.JMenuItem jMenuItemDJ08;
    private javax.swing.JMenuItem jMenuItemGasto;
    private javax.swing.JMenuItem jMenuItemGeneralResumen;
    private javax.swing.JMenuItem jMenuItemGenerarListado;
    private javax.swing.JMenuItem jMenuItemOficinas;
    private javax.swing.JMenuItem jMenuItemOfimatica;
    private javax.swing.JMenuItem jMenuItemOtro;
    private javax.swing.JMenuItem jMenuItemServicio;
    private javax.swing.JMenuItem jMenuItemTrabajadores;
    private javax.swing.JMenuItem jMenuItemTramite;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JMenu jMenuOperacionServiciosAsAt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinnerDate;
    private javax.swing.JTable jTablePagos;
    private javax.swing.JTextArea jTextAreaNota;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNit;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
