/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

/**
 *
 * @author lrmendiburo
 */
public class VentanaAdicionarOtro extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAdicionarOtro
     */
    public VentanaAdicionarOtro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVolver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButtonLimpiar = new javax.swing.JButton();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldConcepto = new javax.swing.JTextField();
        jSpinnerMonto = new javax.swing.JSpinner();
        jLabelMes = new javax.swing.JLabel();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jLabelMes1 = new javax.swing.JLabel();
        jSpinnerDate = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNota = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxOficina = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButtonAceptar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuEstructura = new javax.swing.JMenu();
        jMenuItemOficinas = new javax.swing.JMenuItem();
        jMenuItemTrabajadores = new javax.swing.JMenuItem();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenuOperacionServiciosAsAt = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemDJ08 = new javax.swing.JMenuItem();
        jMenuItemCR09 = new javax.swing.JMenuItem();
        jMenuItemDJ05 = new javax.swing.JMenuItem();
        jMenuItemTramite = new javax.swing.JMenuItem();
        jMenuItemOfimatica = new javax.swing.JMenuItem();
        jMenuItemOtro = new javax.swing.JMenuItem();
        jMenuItemGasto = new javax.swing.JMenuItem();
        jMenuItemServicio = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuClientes = new javax.swing.JMenu();
        jMenuItemClienteTitular = new javax.swing.JMenuItem();
        jMenuItemClienteContratado = new javax.swing.JMenuItem();
        jMenuGeneral = new javax.swing.JMenu();
        jMenuItemGenerarListado = new javax.swing.JMenuItem();
        jMenuItemGeneralResumen = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonVolver.setText("Vover");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Nota:");

        jButtonLimpiar.setText("Limpiar");

        jSpinnerMonto.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 10.0f));

        jLabelMes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelMes.setText("Oficina:");

        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jLabelMes1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelMes1.setText("Mes:");

        jSpinnerDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_WEEK_IN_MONTH));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Adicionar Otros:");

        jTextAreaNota.setColumns(20);
        jTextAreaNota.setRows(5);
        jScrollPane1.setViewportView(jTextAreaNota);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Concepto:");

        jComboBoxOficina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Playa", "Redondel", "Marianao" }));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Monto:");

        jButtonAceptar.setText("Aceptar");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Fecha:");

        jMenuEstructura.setText("Estructura");

        jMenuItemOficinas.setText("Oficinas");
        jMenuEstructura.add(jMenuItemOficinas);

        jMenuItemTrabajadores.setText("Trabajadores");
        jMenuEstructura.add(jMenuItemTrabajadores);

        jMenuItemUsuarios.setText("Usuarios");
        jMenuEstructura.add(jMenuItemUsuarios);

        jMenuBarPrincipal.add(jMenuEstructura);

        jMenuOperacionServiciosAsAt.setText("Operación");

        jMenu1.setText("Ingreso");

        jMenuItemDJ08.setText("DJ08");
        jMenu1.add(jMenuItemDJ08);

        jMenuItemCR09.setText("CR09");
        jMenu1.add(jMenuItemCR09);

        jMenuItemDJ05.setText("DJ05");
        jMenu1.add(jMenuItemDJ05);

        jMenuItemTramite.setText("Trámite");
        jMenu1.add(jMenuItemTramite);

        jMenuItemOfimatica.setText("Ofímatica");
        jMenu1.add(jMenuItemOfimatica);

        jMenuItemOtro.setText("Otro");
        jMenu1.add(jMenuItemOtro);

        jMenuOperacionServiciosAsAt.add(jMenu1);

        jMenuItemGasto.setText("Gasto");
        jMenuOperacionServiciosAsAt.add(jMenuItemGasto);

        jMenuItemServicio.setText("Servicio");
        jMenuOperacionServiciosAsAt.add(jMenuItemServicio);

        jMenuItem1.setText("Servicios Ad/At");
        jMenuOperacionServiciosAsAt.add(jMenuItem1);

        jMenuBarPrincipal.add(jMenuOperacionServiciosAsAt);

        jMenuClientes.setText("Clientes");

        jMenuItemClienteTitular.setText("Cliente Titular");
        jMenuClientes.add(jMenuItemClienteTitular);

        jMenuItemClienteContratado.setText("Cliente Contratado");
        jMenuClientes.add(jMenuItemClienteContratado);

        jMenuBarPrincipal.add(jMenuClientes);

        jMenuGeneral.setText("General");

        jMenuItemGenerarListado.setText("Generar Listado");
        jMenuGeneral.add(jMenuItemGenerarListado);

        jMenuItemGeneralResumen.setText("Generar Resumen");
        jMenuGeneral.add(jMenuItemGeneralResumen);

        jMenuBarPrincipal.add(jMenuGeneral);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabelMes1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabelMes))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSpinnerDate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxMes, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 224, Short.MAX_VALUE)
                                .addComponent(jButtonAceptar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonLimpiar)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxOficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldID)
                                .addComponent(jTextFieldConcepto)
                                .addComponent(jSpinnerMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jSpinnerMonto, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMes1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jSpinnerDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxOficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMes))
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonVolver)
                            .addComponent(jButtonLimpiar)
                            .addComponent(jButtonAceptar))
                        .addGap(18, 18, 18))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdicionarOtro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdicionarOtro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdicionarOtro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdicionarOtro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdicionarOtro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JComboBox<String> jComboBoxOficina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelMes;
    private javax.swing.JLabel jLabelMes1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenu jMenuEstructura;
    private javax.swing.JMenu jMenuGeneral;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemCR09;
    private javax.swing.JMenuItem jMenuItemClienteContratado;
    private javax.swing.JMenuItem jMenuItemClienteTitular;
    private javax.swing.JMenuItem jMenuItemDJ05;
    private javax.swing.JMenuItem jMenuItemDJ08;
    private javax.swing.JMenuItem jMenuItemGasto;
    private javax.swing.JMenuItem jMenuItemGeneralResumen;
    private javax.swing.JMenuItem jMenuItemGenerarListado;
    private javax.swing.JMenuItem jMenuItemOficinas;
    private javax.swing.JMenuItem jMenuItemOfimatica;
    private javax.swing.JMenuItem jMenuItemOtro;
    private javax.swing.JMenuItem jMenuItemServicio;
    private javax.swing.JMenuItem jMenuItemTrabajadores;
    private javax.swing.JMenuItem jMenuItemTramite;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JMenu jMenuOperacionServiciosAsAt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerDate;
    private javax.swing.JSpinner jSpinnerMonto;
    private javax.swing.JTextArea jTextAreaNota;
    private javax.swing.JTextField jTextFieldConcepto;
    private javax.swing.JTextField jTextFieldID;
    // End of variables declaration//GEN-END:variables
}
